[project]
name = "halloechen-website"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "grpcio>=1.83.0",
    "ortools>=9.15.6755",
]

[dependency-groups]
dev = [
    "grpcio-tools>=1.81.1",
    "ruff>=0.16.0",
]

[tool.ruff]
extend-exclude = [
    "**/*_pb2.py",
    "**/*_pb2_grpc.py",
    "**/*_pb2.pyi",
]
